import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Form Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
