import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Form Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
    <ClerkProvider>
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        <SignedOut>
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        <Header SignInButton={SignInButton} />
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
